### PR TITLE
Updating for recent emacs

### PR DESCRIPTION
**Pull request by KoviRobi**
This
* gets rid of the 'cl functions
* puts an autoload cookie into the file

### CODE REVIEW

**Comment by KoviRobi** [comment]
Should I bump version number as well?

**Comment by lifelike** [comment]
Thanks!

I was going to bump the version number soon anyway with a few more minor additions made recently, so I just bump it once and include this merge first.

**Comment by lifelike** [comment]
What does the autoload line do?

**Comment by lifelike** [comment]
Merged and bumped version to 0.6.

**Comment by KoviRobi** [comment]
Thanks,
You can read more about the autoload cookie here https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html if you are curious (I got an e-mail about a comment asking what does the autoload line do, but could not see it here to reply)

**Comment by lifelike** [comment]
I removed the comment after finding that documentation. Thanks again!

**Pull request merged**
